pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
pip install nb-cli
pip install nonebot-adapter-onebot
pip install pillow
pip install cn2an
pip install psutil
pip install qrcode
pip install aiocache
pip install aiohttp
pip install jieba
pip install aiofiles
pip install imageio
pip install pyzbar
pip install fontTools
pip install ujson
pip install pinyin
pip install pyenchant
pip install opencv-python
pip install emoji
pip install pypinyin
pip install dateparser
pip install lxml
pip install cachetools
pip install bs4
pip install nonebot_plugin_apscheduler
pip install nonebot_plugin_htmlrender
pip install wmi