import base64
import random
import time
from typing import Dict, List, Tuple

a: Dict[str, str] = {
    "m": "q",
    "3": "/",
    "5": ")",
    "y": "e",
    "t": "h",
    "i": "u",
    "a": "}",
    "8": "$",
    "c": "\u007f",
    "1": "-",
    "6": "*",
    "4": "(",
    "2": ".",
    "z": "f",
    "f": "z",
    "h": "t",
    "r": "n",
    "0": ",",
    "7": "+",
    "g": "{",
    "j": "v",
    "w": "k",
    "x": "d",
    "e": "y",
    "l": "p",
    "o": "s",
    "s": "o",
    "v": "j",
    "9": "%",
    "k": "w",
    "q": "m",
    "n": "r",
    "d": "x",
    "u": "i",
    "b": "~",
    "p": "l",
}
b: Dict[str, str] = {
    "A": "!",
    "B": '"',
    "C": "#",
    "D": "$",
    "E": "%",
    "F": "&",
    "G": "'",
    "H": "(",
    "I": ")",
    "J": "*",
    "K": "+",
    "L": ",",
    "M": "-",
    "N": ".",
    "O": "/",
    "P": "0",
    "Q": "1",
    "R": "2",
    "S": "3",
    "T": "4",
    "U": "5",
    "V": "6",
    "W": "7",
    "X": "8",
    "Y": "9",
    "Z": ":",
    "a": ";",
    "b": "<",
    "c": "=",
    "d": ">",
    "e": "?",
    "f": "@",
    "g": "A",
    "h": "B",
    "i": "C",
    "j": "D",
    "k": "E",
    "l": "F",
    "m": "G",
    "n": "H",
    "o": "I",
    "p": "J",
    "q": "K",
    "r": "L",
    "s": "M",
    "t": "N",
    "u": "O",
    "v": "P",
    "w": "Q",
    "x": "R",
    "y": "S",
    "z": "T",
    "0": "U",
    "1": "V",
    "2": "W",
    "3": "X",
    "4": "Y",
    "5": "Z",
    "6": "[",
    "7": "\\",
    "8": "]",
    "9": "^",
    "+": "_",
    "/": "`",
    "=": "~",
}


def get_headers() -> Dict[str, str]:
    def get_sign() -> Tuple[str, str, str]:
        c, r, t, s = (
            "",
            "",
            str(int(time.time())),
            "".join(
                random.sample("".join([chr(l).lower() for l in range(65, 91)]), 11)
            ),
        )
        for i in s + t:
            c += a[i]
        for i in base64.b64encode(c.encode()).decode():
            r += b[i]
        return s, t, f"SIGv1.0|{r}"

    s, t, sign = get_sign()

    return {
        "authority": "pcr-api.himaribot.com",
        "accept": "application/json, text/plain, */*",
        "accept-language": "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6",
        "content-type": "application/json",
        "cookie": "token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjM4NDQsImV4cCI6MTY5MDk5MzYwNywiaWF0IjoxNjkwMzg4ODA3fQ.1VBd6aoIPbM2XNlK66l_VWvZyjg_5eu79z30Sa8Rr4w",
        "origin": "https://kyouka.kengxxiao.com",
        "referer": "https://kyouka.kengxxiao.com/",
        "sec-ch-ua": '"Not/A)Brand";v="99", "Microsoft Edge";v="115", "Chromium";v="115"',
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": '"Windows"',
        "sec-fetch-dest": "empty",
        "sec-fetch-mode": "cors",
        "sec-fetch-site": "cross-site",
        "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.183",
        "x-nonce": s,
        "x-sign": sign,
        "x-timestamp": t,
    }
